### ISSUE TITLE
cant choose a location on kul tiras campaign (table)

### ISSUE THREAD

**Issue by MisterT87** [alarofrunetotem/ChampionCommander#2] opened 2018-08-19 05:39 UTC
Hi, first of all thanks for this addon :)

On the first table ( Where u can choose Championsquest...) this addon works properly.

But on the "Kul Tiras Campaign" table (In Zuldazar - right side from the championstable near  to Nathanos Blightcaller): If ChampionCommander addon is enabled i cant choose any location on Kul Tiras...

Map seems to be freezed then and map animations also skipped...

When I disable ChampionCommander - problem is gone

**Comment by Kelda2006** [comment] 2018-08-19 09:19
Have the same problem. Playing on Alliance side, neither the scouting map in the Harbour Master's office nor the Zandalar Campaign table can be interacted with when the addon is enabled.

Other than that it's all good and no errors are reported ingame.

Thanks, keep up the good work.

**Comment by MisterT87** [comment] 2018-08-19 13:24
Nice to see one more ppl with same problem :)

@Kelda2006 : Can you please keep one location "open" - on Zandalar Campaign table ?

I already did all 3 locations and cant retest it later (for problem fixing) -.-
Please tell me you have at least on location on this table :D

**Comment by alar77** [comment] 2018-10-05 14:39
Issues with maps are popping here and there but I could never reproduce them. I even made a video showing that I could click on maps.
I keep testing but until it happens to me I cant fix it.

**Comment by Metski** [comment] 2018-11-02 11:09
I have the same problem on horde side. I can't interact with the scouting map in The Great Seal to chose a zone for questing. When I disable the addon the map is working correctly, maybe try once again to reproduce it?

**Comment by alar77** [comment] 2019-08-28 15:09
Closed as duplicate of #23

**Closed as completed by alar77** 2019-08-28 15:09 UTC
Labels: question
